### PR TITLE
Localization For Chinese Simplified

### PR DESCRIPTION
**Pull request by song682**

### CODE REVIEW

**Comment by connor135246** [comment]
Thanks for the translation!
I just added another config option in here: https://github.com/connor135246/Campfire-Backport/commit/fcd56aa4659f89d7d46bddb2f18ed9ee441f0a89
Would you like to translate that as well?

**Comment by connor135246** [comment]
I made another change to the config. You can now translate the name of a config option. [See here](https://github.com/connor135246/Campfire-Backport/blob/a973b1ac06bae663cb1f0c7797868c19d1590714/src/main/resources/assets/campfirebackport/lang/en_US.lang#L204-L283).
I also changed the translation key format, so here's your translation in the new format:

```
campfirebackport.config.render_3d=
campfirebackport.config.render_3d.tooltip=若设为 True，营火将会以 3D 模型形式渲染。 (该配置仅客户端)
campfirebackport.config.charcoal=
campfirebackport.config.charcoal.tooltip=若设为 True，普通营火将只能由木炭合成。原版营火只能由煤炭或木炭合成，若不想让玩家用煤炭转化成木炭，请打开此选项。
campfirebackport.config.soul_soil=
campfirebackport.config.soul_soil.tooltip=若设为 True，灵魂营火将只能由 Netherlicious 的灵魂土合成。原版灵魂营火只能由灵魂沙或灵魂土合成，若不想让玩家用煤炭转化成木炭，请打开此选项。 (若 Netherlicious 未安装，这个选项不会工作) 
campfirebackport.config.regen=
campfirebackport.config.regen.tooltip=点燃的营火将会给附近的玩家提供一个再生效果。
campfirebackport.config.regen_settings.reg=
campfirebackport.config.regen_settings.reg.tooltip=第一个值为再生等级 (0-31 的整数) ，第二个值是再生时长 (单位为 Tick)，第三个值是生效半径 (在半径多少的范围内，玩家会受到此效果)，第四个值是生效间隔 (每隔多少 Tick 将会再次给予玩家再生效果)。
campfirebackport.config.regen_settings.soul=
campfirebackport.config.regen_settings.soul.tooltip=第一个值为再生等级 (0-31 的整数) ，第二个值是再生时长 (单位为 Tick)，第三个值是生效半径 (在半径多少的范围内，玩家会受到此效果)，第四个值是生效间隔 (每隔多少 Tick 将会再次给予玩家再生效果)。
campfirebackport.config.auto=
campfirebackport.config.auto.tooltip=该种营火将会遍历每一个熔炉配方来寻找一个继承了 ItemFood 的物品，并将其添加进该营火的配方列表。
campfirebackport.config.auto_blacklist=
campfirebackport.config.auto_blacklist.tooltip=若输入中有该列表中的物品，Auto Recipe Discovery 将不会添加该配方至配方列表中。 【其模式较为固定。模式为: "ore:矿物辞典名" 抑或 "modid:注册名" 、 "modid:注册名:元数据"。若没有元数据 (即注册名后无冒号)，则默认元数据为0；若元数据为空 (即注册名后的冒号后没有数) ，所有在该注册名下的物品都将会被拒绝使用。】
campfirebackport.config.default_cooking_times=
campfirebackport.config.default_cooking_times.tooltip=由 Auto Recipe Discovery 添加或由自定义营火配方添加的烹饪时间 (单位为 Tick) 并不一定一样。第一个值是对于营火而言的，第二个值则是对于灵魂营火而言的。
campfirebackport.config.recipes.reg=
campfirebackport.config.recipes.reg.tooltip=普通营火 营火的自定义食谱列表。 (你亦可以用 CraftTweaker 来自定义。在 GitHub 上查看 Wiki，或使用命令 "/campfirebackport dumpinfo" 来学习如何做。)
campfirebackport.config.recipes.soul=
campfirebackport.config.recipes.soul.tooltip=灵魂营火 营火的自定义食谱列表。 (你亦可以用 CraftTweaker 来自定义。在 GitHub 上查看 Wiki，或使用命令 "/campfirebackport dumpinfo" 来学习如何做。)
campfirebackport.config.recipes_inheritance=
campfirebackport.config.recipes_inheritance.tooltip=可使一种类型的自定义配方继承另一种。这样以后就无需再打一遍。
campfirebackport.config.spawnpointable=
campfirebackport.config.spawnpointable.tooltip=该种营火在点燃的状态下时，可在蹲下的同时，用空手右键点击，设置一个重生点。 来自于 Home Camp ，链接: https://www.curseforge.com/minecraft/mc-mods/home-camp
campfirebackport.config.spawnpointable_alt_trigger=
campfirebackport.config.spawnpointable_alt_trigger.tooltip=
campfirebackport.config.burn_out_on_respawn=
campfirebackport.config.burn_out_on_respawn.tooltip=当你用该种营火重生时，该种营火将会燃尽。默认情况下信号营火将不会燃尽，详见燃尽 (信号营火)。
campfirebackport.config.automation=
campfirebackport.config.automation.tooltip=漏斗和其他自动化装置会将物品从该种营火的侧面输入到该种营火中。
campfirebackport.config.default_unlit=
campfirebackport.config.default_unlit.tooltip=默认合成未点燃的营火，而非点燃的；破坏该营火亦是如此掉落。（需重启游戏以应用此更改) 
campfirebackport.config.remember_state=
campfirebackport.config.remember_state.tooltip=该种营火将会在破坏后掉落破坏时的状态的物品。 (例: 破坏不点燃的就掉不点燃的，不管 Unlit by Default设置)
campfirebackport.config.silk=
campfirebackport.config.silk.tooltip=是否需要精准采集来获得营火。
campfirebackport.config.rained_out=
campfirebackport.config.rained_out.tooltip=该种营火在雨中会被浇灭；其特别慢... 默认情况下信号营火将不会燃尽，详见燃尽 (信号营火)。
campfirebackport.config.works_underwater=
campfirebackport.config.works_underwater.tooltip=该种营火就算被水浇也不会熄灭。
campfirebackport.config.damaging=
campfirebackport.config.damaging.tooltip=走在该种营火上面的生物将不会燃烧。 (该设置在村庄中很有用)
campfirebackport.config.vis_costs=
campfirebackport.config.vis_costs.tooltip=当安装有神秘时代时，用法杖点燃/熄灭营火时所需多少火要素/水要素。顺序为: 熄灭营火所需水要素量；熄灭灵魂营火所需水要素量；点燃营火所需火要素量；点燃灵魂营火所需火要素量。将其中一种设为 0 以禁用。
campfirebackport.config.burn_out_timer=
campfirebackport.config.burn_out_timer.tooltip=营火燃尽所需时间 (单位为 Tick)，设为 -1 以禁用并使其永久存在，第一个值是对于营火而言的，第二个值则是对于灵魂营火而言的。 随着所给值而有不同。默认情况下信号营火将不会燃尽，详见燃尽 (信号营火)。
campfirebackport.config.burn_out_rules=
campfirebackport.config.burn_out_rules.tooltip=此处你可设置仅针对生物群系或维度的计时器。 (你亦可以用 CraftTweaker 来自定义。在 GitHub 上查看 Wiki，或使用命令 "/campfirebackport dumpinfo" 来学习如何做。)
campfirebackport.config.signals_burn_out=
campfirebackport.config.signals_burn_out.tooltip=信号萤火将不会或因雨而浇灭燃尽计时器或在重生时燃尽。该设置可以使其燃尽。
campfirebackport.config.burn_to_nothing=
campfirebackport.config.burn_to_nothing.tooltip=该设置可以设置燃尽/浇灭时，被破坏的几率。当用精准采集破坏时营火将会掉落其物品形式，或者是掉落合成它的物品.(浮点值，0.0-1.0，0.1=10%%，第一个值是对于营火而言的，第二个值则是对于灵魂营火而言的)
campfirebackport.config.burn_out_as_item=
campfirebackport.config.burn_out_as_item.tooltip=该种营火于其被取代前开始燃尽。 其将会计算其燃尽后成为一物品所需时间，不管是在世界中，亦或在玩家物品栏内。 (值得注意的是，其不在前述所处的位置时，计时器将会暂停；但若再到前述位置，则又会开始。)
campfirebackport.config.signal_fire_blocks=
campfirebackport.config.signal_fire_blocks.tooltip=能够置于营火下的且使其变为信号营火的方块。信号营火的烟相较于普通的飘的更高。【其模式较为固定。模式为: "ore:矿物辞典名" 抑或 "modid:注册名" 、 "modid:注册名:元数据"。若没有元数据 (即注册名后无冒号)，则该注册名下所有物品均可；若元数据为空 (即注册名后的冒号后没有数) ，所有在该注册名下的物品都将会被拒绝使用。】
campfirebackport.config.campfire_drops=
campfirebackport.config.campfire_drops.tooltip=非精准采集工具破坏营火的掉落物。第一行条目是对于营火而言的，第二行条目则是对于灵魂营火而言的。若条目为空或无此物品，将会用原版的物品。 (原版物品为普通营火对应两个木炭，灵魂营火对应一个灵魂沙) 【其模式较为固定。模式为: "ore:矿物辞典名" 抑或 "modid:注册名@数量" 、 "modid:注册名:元数据@数量" 。若没有元数据 (即注册名后无冒号)，则默认元数据为0；若元数据为空 (即注册名后的冒号后没有数) ，所有在该注册名下的物品都将会被拒绝使用。你亦可以用 CraftTweaker 来自定义。在 GitHub 上查看 Wiki，或使用命令 "/campfirebackport dumpinfo" 来学习如何做。】 
campfirebackport.config.colourful_smoke=
campfirebackport.config.colourful_smoke.tooltip=被红石充能时，该营火将会升起与下方方块相对应颜色的烟 (颜色基于地图上该方块的颜色)。与自定义信号营火相搭配效果更佳。来自于 Colorful Campfire Smoke, 链接: https://www.curseforge.com/minecraft/mc-mods/colorful-campfire-smoke
campfirebackport.config.dispenser_blacklist=
campfirebackport.config.dispenser_blacklist.tooltip=不接受来自于自定义点火物品/灭火物品的发射器行为中，发射器行为是可发射的。 【其模式较为固定。模式为: "modid:注册名"】
campfirebackport.config.state_changers.extinguisher.reg=
campfirebackport.config.state_changers.extinguisher.reg.tooltip=普通营火营火的自定义点火物品。 (你亦可以用 CraftTweaker 来自定义。在 GitHub 上查看 Wiki，或使用命令 "/campfirebackport dumpinfo" 来学习如何做。)
campfirebackport.config.state_changers.extinguisher.soul=
campfirebackport.config.state_changers.extinguisher.soul.tooltip=灵魂营火营火的自定义点火物品。 (你亦可以用 CraftTweaker 来自定义。在 GitHub 上查看 Wiki，或使用命令 "/campfirebackport dumpinfo" 来学习如何做。)
campfirebackport.config.state_changers.ignitor.reg=
campfirebackport.config.state_changers.ignitor.reg.tooltip=普通营火营火的自定义灭火物品。 (你亦可以用 CraftTweaker 来自定义。在 GitHub 上查看 Wiki，或使用命令 "/campfirebackport dumpinfo" 来学习如何做。)
campfirebackport.config.state_changers.ignitor.soul=
campfirebackport.config.state_changers.ignitor.soul.tooltip=灵魂营火营火的自定义灭火物品。 (你亦可以用 CraftTweaker 来自定义。在 GitHub 上查看 Wiki，或使用命令 "/campfirebackport dumpinfo" 来学习如何做。)
campfirebackport.config.extinguishers_inheritance=
campfirebackport.config.extinguishers_inheritance.tooltip=可使一种类型的自定义点火物品继承另一种。这样以后就无需再打一遍。
campfirebackport.config.ignitors_inheritance=
campfirebackport.config.ignitors_inheritance.tooltip=可使一种类型的自定义灭火物品继承另一种。这样以后就无需再打一遍。
campfirebackport.config.print_recipes=
campfirebackport.config.print_recipes.tooltip=若设为 True, 在重载配置时，最终生成一个有着以下内容的列表:自定义配方、自定义点火物品/灭火物品和维度/生物群系的计时器。
campfirebackport.config.suppress_errors=
campfirebackport.config.suppress_errors.tooltip=若设为 True, 在重载配置时，不生成一个有着以下内容的列表:自定义配方、自定义点火物品/灭火物品和维度/生物群系的计时器。但会提醒前述内容中的无效值。
```
If you can fill in the blank ones, that would be great!

**Comment by song682** [comment]
Sorry to have kept you waiting. I'll fill in all the blanks.
And by the way,
I'm wondering if I can see the original text.

**Comment by connor135246** [comment]
> And by the way,
> I'm wondering if I can see the original text.

You can find the original text in en_US.lang:
https://github.com/connor135246/Campfire-Backport/blob/95d0a7bdcc016bce6163a240d2068374f082ca9a/src/main/resources/assets/campfirebackport/lang/en_US.lang#L204-L285

**Comment by song682** [comment]
Final version is completed.

**Pull request merged**
